const {
  VITE_SHATOT_API_KEY,
  VITE_SHATOT_AUTH_DOMAIN,
  VITE_SHATOT_PROJECT_ID,
  VITE_SHATOT_STORAGE_BUCKET,
  VITE_SHATOT_MESSAGING_SENDER_ID,
  VITE_SHATOT_APP_ID,
} = import.meta.env;

const viteEnv = {
  apik: VITE_SHATOT_API_KEY,
  authDomain: VITE_SHATOT_AUTH_DOMAIN,
  projectId: VITE_SHATOT_PROJECT_ID,
  storageBucket: VITE_SHATOT_STORAGE_BUCKET,
  messagingSenderId: VITE_SHATOT_MESSAGING_SENDER_ID,
  appId: VITE_SHATOT_APP_ID,
};

export { viteEnv };
